import React from "react";
import Navbar from "../components/Navbar";
import variables from "../styles/variables.module.scss";
import Head from "next/head";
import SearchBox from "../components/SearchBox.jsx";
import blog from "../components/data";
import bgImg from "../assets/tech.jpg";
import avatar from "../assets/men.jpg";
import buttons from "../styles/buttons.module.scss";

import { BiLike, BiComment } from "react-icons/bi";
const Content = () => {
  const trending = [
    "programming","data science","technology","self improvement","writing","relationships","machine learning","productivity","politics"
  ]
  return (
    <>
      <Head>
        <title>Blog - Home🏠</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={variables.content_page}>
        <Navbar />
        <SearchBox />
       
        {/* main page contents here */}
        <div className={variables.cards_box}>
          <div className={variables.card_box_cont}>
              {blog.map((item,key)=>(
                <div className={variables.card_cont} key={key}>
                <div className={variables.card_text_content}>
                    <span>
                      <img src={avatar.src} className={variables.avatar_img_card}/>
                      <p className={variables.avatar_text_card}>{item.author}</p>
                    </span>
                    <h3>{item.title}</h3>
                    <p className={variables.card_text_desc}>{item.desc}</p>
                    <div className={variables.card_add_info}>
                      <p>{item.datePublished}</p>
                      <p>.</p>
                      <p>{item.readTime}</p>
                      <p>.</p>
                      {item.tags.map((item,key)=>(<button className={buttons.tag} key={key}>
                        {item}
                      </button>))}
                      
                    </div>
                </div>
                <div className={variables.card_cont_img}>
                  <img className={variables.card_c_img} src={bgImg.src}/>
                </div>
              </div>
              ))}
          </div>
          <div className={variables.button_card_box}>
            <h3>Discover more of what matters to you</h3>
            <div className={variables.buttons_cont}>
                {trending.map((item,key)=>(
                  <button key={key} className={`${buttons.tag}`+` ${buttons.big}`}>
                    {item}
                  </button>
                ))}  
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Content;
